In [ ]:
!pip install keras

In [ ]:
!pip install np_utils

     -------------------------------------- 62.0/62.0 kB 470.4 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for np_utils: filename=np_utils-0.6.0-py3-none-any.whl size=56454 sha256=ebd72ab4fca520ef10c6e2733e0d09f968c521d6370cf6d7c2f1123420266a57
  Stored in directory: c:\users\yousf\appdata\local\pip\cache\wheels\c9\5e\52\216e2fa9b02d46b865d8160e7fe29dcf98f89a2fb7be254877
Successfully built np_utils


In [44]:
import numpy as np
import cv2
from keras.datasets import mnist
from keras import utils as np_utils

from keras import backend as K
K.set_image_data_format('channels_last')
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers import Conv2D
from keras.layers import MaxPooling2D

In [12]:
(X_train, y_train),(X_test, y_test)= mnist.load_data()

In [13]:
# reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 1, 28,28).astype
('float32')
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28).astype
('float32')

'float32'

In [14]:
#one hot encode outputs
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]

In [24]:
def get_data_mnist():
    # load data
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
    # reshape to be [samples][pixels][width][height]
    X_train = X_train.reshape(X_train.shape[0],  28, 28,1).astype('float32')
    X_test = X_test.reshape(X_test.shape[0], 28, 28,1).astype('float32')


    # normalize inputs from 0-255 to 0-1
    X_train = X_train / 255
    X_test = X_test / 255
    # one hot encode outputs
    y_train = np_utils.to_categorical(y_train)
    y_test = np_utils.to_categorical(y_test)
    num_classes = y_test.shape[1]
    return (X_train, y_train), (X_test, y_test), num_classes


In [25]:

def small_model(num_classes):
    model = Sequential()

    model.add(Conv2D(64, (3, 3), input_shape=( 28, 28,1), activation='relu'))
    model.add(Conv2D(32, (3, 3), activation='relu'))

    model.add(Flatten())

    model.add(Dense(num_classes, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

num_classes = 10
model = small_model(num_classes)

In [19]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 26, 26, 64)        640       
                                                                 
 conv2d_4 (Conv2D)           (None, 24, 24, 32)        18464     
                                                                 
 flatten_1 (Flatten)         (None, 18432)             0         
                                                                 
 dense_1 (Dense)             (None, 10)                184330    
                                                                 
Total params: 203434 (794.66 KB)
Trainable params: 203434 (794.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
(X_train, y_train), (X_test, y_test), num_classes = get_data_mnist()

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)


Epoch 1/10
300/300 [==============================] - 159s 528ms/step - loss: 0.0159 - accuracy: 0.9948 - val_loss: 0.1456 - val_accuracy: 0.9781
Epoch 2/10
300/300 [==============================] - 150s 500ms/step - loss: 0.0125 - accuracy: 0.9958 - val_loss: 0.1562 - val_accuracy: 0.9746
Epoch 3/10
300/300 [==============================] - 150s 500ms/step - loss: 0.0086 - accuracy: 0.9971 - val_loss: 0.1392 - val_accuracy: 0.9777
Epoch 4/10
300/300 [==============================] - 153s 509ms/step - loss: 0.0090 - accuracy: 0.9971 - val_loss: 0.1634 - val_accuracy: 0.9780
Epoch 5/10
300/300 [==============================] - 152s 506ms/step - loss: 0.0077 - accuracy: 0.9978 - val_loss: 0.1637 - val_accuracy: 0.9782
Epoch 6/10
300/300 [==============================] - 154s 512ms/step - loss: 0.0109 - accuracy: 0.9967 - val_loss: 0.1810 - val_accuracy: 0.9755
Epoch 7/10
300/300 [==============================] - 148s 495ms/step - loss: 0.0098 - accuracy: 0.9970 - val_loss: 0.1861 -

In [22]:
def print_model_error_rate(model, X_test, y_test):
  # Final evaluation of the model
  scores = model.evaluate(X_test, y_test, verbose=0)
  print("Model score : %.2f%%" % (scores[1]*100))
  print("Model error rate : %.2f%%" % (100-scores[1]*100))
#BEFORE NORMALISATION
print_model_error_rate(model,X_test,y_test)

Model score : 97.82%
Model error rate : 2.18%


In [26]:
(X_train, y_train), (X_test, y_test), num_classes = get_data_mnist()

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)


Epoch 1/10
300/300 [==============================] - 157s 520ms/step - loss: 0.2280 - accuracy: 0.9366 - val_loss: 0.0643 - val_accuracy: 0.9810
Epoch 2/10
300/300 [==============================] - 153s 509ms/step - loss: 0.0622 - accuracy: 0.9811 - val_loss: 0.0513 - val_accuracy: 0.9847
Epoch 3/10
300/300 [==============================] - 156s 519ms/step - loss: 0.0431 - accuracy: 0.9869 - val_loss: 0.0504 - val_accuracy: 0.9842
Epoch 4/10
300/300 [==============================] - 157s 522ms/step - loss: 0.0319 - accuracy: 0.9898 - val_loss: 0.0417 - val_accuracy: 0.9866
Epoch 5/10
300/300 [==============================] - 148s 495ms/step - loss: 0.0238 - accuracy: 0.9926 - val_loss: 0.0475 - val_accuracy: 0.9856
Epoch 6/10
300/300 [==============================] - 150s 500ms/step - loss: 0.0198 - accuracy: 0.9934 - val_loss: 0.0457 - val_accuracy: 0.9865
Epoch 7/10
300/300 [==============================] - 154s 513ms/step - loss: 0.0147 - accuracy: 0.9957 - val_loss: 0.0469 -

In [27]:
#AFTER NORMALISATION
print_model_error_rate(model,X_test,y_test)

Model score : 98.58%
Model error rate : 1.42%


In [32]:
def medium_model():
    # create model
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(28, 28,1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [33]:
model_medium = medium_model()

model_medium.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)


Epoch 1/10
300/300 [==============================] - 35s 113ms/step - loss: 0.2428 - accuracy: 0.9296 - val_loss: 0.0820 - val_accuracy: 0.9753
Epoch 2/10
300/300 [==============================] - 30s 101ms/step - loss: 0.0744 - accuracy: 0.9779 - val_loss: 0.0575 - val_accuracy: 0.9823
Epoch 3/10
300/300 [==============================] - 32s 108ms/step - loss: 0.0527 - accuracy: 0.9842 - val_loss: 0.0401 - val_accuracy: 0.9873
Epoch 4/10
300/300 [==============================] - 31s 102ms/step - loss: 0.0410 - accuracy: 0.9878 - val_loss: 0.0361 - val_accuracy: 0.9879
Epoch 5/10
300/300 [==============================] - 32s 106ms/step - loss: 0.0339 - accuracy: 0.9892 - val_loss: 0.0370 - val_accuracy: 0.9871
Epoch 6/10
300/300 [==============================] - 32s 105ms/step - loss: 0.0274 - accuracy: 0.9917 - val_loss: 0.0338 - val_accuracy: 0.9887
Epoch 7/10
300/300 [==============================] - 31s 102ms/step - loss: 0.0230 - accuracy: 0.9924 - val_loss: 0.0352 - val_ac

In [34]:
print_model_error_rate(model_medium,X_test,y_test)

Model score : 98.99%
Model error rate : 1.01%


In [35]:
def large_model():
    # create model
    model = Sequential()
    model.add(Conv2D(30, (5, 5), input_shape=(28, 28,1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(15, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [36]:
model_large = large_model()

model_large.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)


Epoch 1/10
300/300 [==============================] - 38s 123ms/step - loss: 0.3595 - accuracy: 0.8885 - val_loss: 0.0792 - val_accuracy: 0.9748
Epoch 2/10
300/300 [==============================] - 37s 124ms/step - loss: 0.0940 - accuracy: 0.9707 - val_loss: 0.0510 - val_accuracy: 0.9847
Epoch 3/10
300/300 [==============================] - 35s 118ms/step - loss: 0.0694 - accuracy: 0.9779 - val_loss: 0.0442 - val_accuracy: 0.9859
Epoch 4/10
300/300 [==============================] - 38s 125ms/step - loss: 0.0572 - accuracy: 0.9814 - val_loss: 0.0380 - val_accuracy: 0.9874
Epoch 5/10
300/300 [==============================] - 36s 120ms/step - loss: 0.0484 - accuracy: 0.9846 - val_loss: 0.0308 - val_accuracy: 0.9908
Epoch 6/10
300/300 [==============================] - 35s 115ms/step - loss: 0.0420 - accuracy: 0.9865 - val_loss: 0.0307 - val_accuracy: 0.9897
Epoch 7/10
300/300 [==============================] - 36s 118ms/step - loss: 0.0368 - accuracy: 0.9880 - val_loss: 0.0296 - val_ac

In [37]:
print_model_error_rate(model_large,X_test,y_test)

Model score : 99.29%
Model error rate : 0.71%


In [38]:
from keras.models import model_from_json

In [40]:
def save_keras_model(model, filename):
  # serialize model to JSON
  model_json = model.to_json()
  with open(filename+".json", "w") as json_file:
    json_file.write(model_json)
  # serialize weights to HDF5
  model.save_weights(filename+".h5")

In [41]:
save_keras_model(model,"small_model")
save_keras_model(model_medium,"medium_model")
save_keras_model(model_large,"large_model")

In [42]:
def load_keras_model(filename):
  # load json and create model
  json_file = open(filename+".json", 'r')
  loaded_model_json = json_file.read()
  json_file.close()
  loaded_model = model_from_json(loaded_model_json)
  # load weights into new model
  loaded_model.load_weights(filename+".h5")
  return loaded_model

In [43]:
small_model=load_keras_model("small_model")
small_model.summary()
medium_model=load_keras_model("medium_model")
medium_model.summary()
large_model=load_keras_model("large_model")
large_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_5 (Conv2D)           (None, 26, 26, 64)        640       
                                                                 
 conv2d_6 (Conv2D)           (None, 24, 24, 32)        18464     
                                                                 
 flatten_2 (Flatten)         (None, 18432)             0         
                                                                 
 dense_2 (Dense)             (None, 10)                184330    
                                                                 
Total params: 203434 (794.66 KB)
Trainable params: 203434 (794.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Par

 Now we can make predictions with our models

In [55]:
def test(model):
  # Load the images and preprocess them
  image_files = [f"/content/images/{i}.jpg" for i in range(10) ]
  images = []

  for file in image_files:
      img = cv2.imread(file, cv2.IMREAD_GRAYSCALE)  # Load image as grayscale
      img = cv2.resize(img, (28, 28))  # Resize the image to match the input shape
      img = img.astype('float32') / 255  # Normalize the pixel values
      img = np.expand_dims(img, axis=-1)  # Add the channel dimension
      images.append(img)

  images = np.array(images)

  # Make predictions
  predictions = model.predict(images)

  # Interpret the predictions and get the class labels
  predicted_labels = np.argmax(predictions, axis=1)
  print(predicted_labels)


### Predictions with small model

In [56]:
test(small_model)

1/1 [==============================] - 0s 25ms/step
[0 1 2 3 4 5 6 7 8 9]


The model correctly predicts all the images of integers from 0 to 9

### Predictions with medium model

In [51]:
test(medium_model)

1/1 [==============================] - 0s 65ms/step
[0 1 2 3 4 5 6 7 8 9]


The model correctly predicts all the images of integers from 0 to 9

### Predictions with large model

In [52]:
test(large_model)

1/1 [==============================] - 0s 89ms/step
[0 1 2 3 4 5 6 7 8 9]


The model correctly predicts all the images of integers from 0 to 9